---
galaxy_info:
  author: Adria Galin Figueras
  description: Set up message of the day (motd)
  company: Adria Galin
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - motd
dependencies: []
