---

- name: postgresql.yml | All roles
  hosts: postgresql
  become: true

  roles:
    - { role: common,                   tags: ["common"] }
    # - { role: ANXS.postgresql,          tags: ["postgresql"] }