---

- name: webservers.yml | All roles
  hosts: webservers
  become: true

  collections:
    - nginxinc.nginx_core

  roles:
    - { role: common,                   tags: ["common"] }
    - { role: nginx,                    tags: ["nginx"] }

